Added EpiLogov2.0 extension
NetLogo/NetLogo-Libraries pull request #35
Opened 2020-02-10 17:19 UTC by JakeSaunders1995

Added Extension for epidemiological modelling

2020-02-14 15:58 UTC, LaCuneta requested changes
Hey @JakeSaunders1995, thank you for your contribution.  I left a couple notes on changes to the `libraries.conf` file.  In addition, the zip file contains an inner `epilogo` folder that actually holds the `epilogo.jar` file.  That jar file should be in the zip file directly, not in a sub-folder.  A more visual description of this problem is [on our wiki page](https://github.com/NetLogo/NetLogo-Libraries/wiki/Submission-workflow#extension-submission-or-update).  

One more comment, not something you must change, but just an observation.  I see in your docs you separated primitive words with camel case, like `inputNewDemographic`.  NetLogo style is to use kebab case for word separation in primitives, like `input-new-demographic`.  Again, you don't have to change this, just pointing it out in case you were unaware.  

Once the zip file update and couple library file updates are made, we should be able to get this merged.  Thanks again.

2020-02-14 15:58 UTC, LaCuneta commented on libraries.conf
> +    downloadURL: "https://github.com/JakeSaunders1995/EpiLogo/tree/master/epilogo"
The `downloadURL` should point to the final location of the zip file in this repository, which would be: `https://raw.githubusercontent.com/NetLogo/NetLogo-Libraries/6.1/extensions/epilogo-2.0.0.zip`

2020-02-14 15:58 UTC, LaCuneta commented on libraries.conf
> +
Extra line break here can be removed.

2020-02-17 11:43 UTC, JakeSaunders1995 commented
I believe i have corrected all of the issues identified including the method name formatting to kebab case.

Kind regards
Jake

2020-02-17 15:57 UTC, LaCuneta approved these changes

2020-02-17 15:58 UTC, merged