EpiLogo v4.0.0
NetLogo/NetLogo-Libraries pull request #40
Opened 2020-12-29 16:33 UTC by JakeSaunders1995

The final update to EpiLogo.

- Improved pathfinding using A* 
- Better population initialisation from input files 
- Improve disease mechanics 
- New agent scheduling format

2021-01-04 15:36 UTC, LaCuneta reviewed
Hey Jake,

Thank you for your contribution!  Just a couple small issues.  The zip file name needs to be updated for the `downloadURL` field in the `libraries.conf` file.  Also, the zip file contains an `epilogo` folder instead of directly containing the jar and other files.  There is more explanation in this section of the wiki:  https://github.com/NetLogo/NetLogo-Libraries/wiki/Submission-workflow#extension-submission-or-update

Once those two issues are fixed, we can get this merged.  Let me know if you have any questions.

2021-01-04 15:36 UTC, LaCuneta commented on libraries.conf
>      downloadURL: "https://raw.githubusercontent.com/NetLogo/NetLogo-Libraries/6.1/extensions/epilogo-3.0.0.zip"
The `downloadURL` will need to be updated to point to the 4.0.0 zip file.

2021-02-04 02:36 UTC, JakeSaunders1995 commented on libraries.conf
>      downloadURL: "https://raw.githubusercontent.com/NetLogo/NetLogo-Libraries/6.1/extensions/epilogo-3.0.0.zip"
Hi this should now be resolved

2021-02-04 14:51 UTC, LaCuneta requested changes
This is close, thank you for the updates!  The `epilogo-4.0.0.zip` file is now correctly setup and the `libraries.conf` file is correct, too.

With the last commit, though, an extra folder was added, `extensions/epilogo-4.0.0/` with a couple extra files in it: https://github.com/NetLogo/NetLogo-Libraries/pull/40/commits/3a704a8e5a9a1516bd57e466a13e08357da5026b  That was probably some work you did to create the proper zip file.  Once that folder and files are removed, this will be good to merge.

Thanks again for your contribution.

2021-02-16 14:41 UTC, LaCuneta approved these changes
Looks good, thank you!

2021-02-16 14:42 UTC, merged