Mgr 1.0.1
NetLogo/NetLogo-Libraries pull request #42
Opened 2021-01-07 11:45 UTC by garypolhill

Sorry bug (and mgr 1.0 was badly configured anyway)

2021-01-15 17:05 UTC, LaCuneta requested changes
Hey Gary!  Thank you so much for the contribution, this looks like a handy extension.  I tested the zip file out and it worked fine. 

I left a couple notes on the `libraries.conf` file, the version is still at 1.0 there.

Also, I think you may need to rebase on to the latest 6.1 branch.  It seems like the branch you used was very old, from before the bit string extension was merged.  If you fetch and pull to the latest `6.1` and then rebase your mgr extension changes on top of that, I think it will clear the conflicts.

Let me know if you have any questions, and thanks again.

2021-01-15 17:05 UTC, LaCuneta commented on libraries.conf
> +    version: "1.0"
Should this be 1.0.1?

2021-01-15 17:05 UTC, LaCuneta commented on libraries.conf
> +    downloadURL: "https://raw.githubusercontent.com/NetLogo/NetLogo-Libraries/6.1/extensions/mgr-1.0.zip"
Link should be to `mgr-1.0.1.zip`, I think.

2021-01-29 14:56 UTC, garypolhill commented on libraries.conf
> +    version: "1.0"
Yes. Done

2021-01-29 14:56 UTC, garypolhill commented on libraries.conf
> +    downloadURL: "https://raw.githubusercontent.com/NetLogo/NetLogo-Libraries/6.1/extensions/mgr-1.0.zip"
Yes done.

2021-01-29 17:30 UTC, LaCuneta commented
Hey Gary, thanks for getting the `libraries.conf` file updated, those changes look good.  We still have the conflict from the bitstring extension commit being there.  I think it should just be a matter of rebasing your local `mgr-1.0.1` branch against our current `6.1` branch then force pushing the results up to your forked repository to update the PR.  Let me know if you need more details on the steps involved.

2021-10-14 13:33 UTC, LaCuneta commented
Closing this in favor of PR #48

2021-10-14 13:33 UTC, closed without merging